version: '3.8'
services:
  user-registration-microservice:
    container_name: user-registration-microservice-container
    image: ghcr.io/mitchell2001b/userregistrationservice:main
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}
    networks:
      - messagebus_semester6_network
    depends_on:
      - mysql-db

  api-gateway:
    image: api-gateway:latest
    build:
      context: ../ApiGateway
    ports:
      - "8585:8585"
    networks:
      - messagebus_semester6_network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_DOCKER_PORT}:${MYSQLDB_LOCAL_PORT}"
    networks:
      - messagebus_semester6_network

  zookeeper:
    container_name: zookeeperContainer
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - messagebus_semester6_network

  kafka:
      container_name: kafkaContainer
      image: confluentinc/cp-kafka:6.2.1
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      networks:
        - messagebus_semester6_network

networks:
  messagebus_semester6_network:

